'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, ChevronUp, Code2, Copy, Expand, GitFork as Github, MoveRight, Pause, Play } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from '@/components/ui/dialog';

const repo = 'https://github.com/awesomeNabi/Geek-Mind';
const sections = [['overview', 'One runtime.'], ['closed-loop', 'Perception to action.'], ['architecture', 'Architecture.'], ['embodiments', 'Multiple embodiments.'], ['demonstration', 'In the real world.'], ['resources', 'Explore the project.']];
const stages = [
  ['Observe', 'Voice · text · vision', 'Collect the instruction, the scene, and live robot state.'],
  ['Fuse', 'Language-aligned context', 'Bring observations, memory, and available tools into one context.'],
  ['Plan', 'Shared Cortex loop', 'Decompose the task and select tools for the next step.'],
  ['Execute', 'Embodiment adapters', 'Validate and route semantic actions to the appropriate robot.'],
  ['Verify', 'Execution feedback', 'Check the result and feed it back into the next planning cycle.'],
];
const profiles = [
  { id: 'go2', label: 'Unitree Go2', kind: 'MOBILE EMBODIMENT', title: 'Move through the world.', description: 'Voice interaction, live robot state, and visual perception meet a mobile base. Go2 supports native navigation or a Mid360-based navigation stack.', image: 'unitree-go2.png', alt: 'Unitree Go2 quadruped robot', tags: ['D435 vision', 'Native / Mid360 navigation', 'Voice interaction'], doc: 'HUMBLE_SETUP.md', note: 'Ubuntu 22.04 + ROS 2 Humble deployment focuses on Go2 + Mid360. ARX is disabled in this profile.' },
  { id: 'arx', label: 'ARX X5', kind: 'MANIPULATION EMBODIMENT', title: 'Turn intent into interaction.', description: 'RGB-D perception and grasp planning connect to arm and gripper execution. Joint and end-effector state return to the same high-level feedback path.', image: 'arx-x5.png', alt: 'ARX X5 robotic arm and gripper', tags: ['RGB-D perception', 'Grasp planning', 'Arm & gripper feedback'], doc: 'STARTUP.md', note: 'Arm deployment requires its own hardware, connectors, and compatible environment.' },
  { id: 'combined', label: 'Go2 + ARX X5', kind: 'MOBILE MANIPULATION', title: 'Navigate. Grasp. Deliver.', description: 'Combine mobility and manipulation through coordinated navigation, grasping, and delivery tasks. Each embodiment keeps its own execution path while sharing task context.', image: 'unitree-go2.png', alt: 'Go2 mobile base for the combined deployment profile', tags: ['Coordinated navigation', 'Grasping', 'Delivery tasks'], doc: 'STARTUP.md', note: 'The combined startup guide describes the legacy Go2 + ARX / ROS 2 Foxy workflow. It is separate from the Humble profile.' },
];
function Heading({ number, title, id }: { number: string; title: string; id: string }) {
  return <div className="section-heading"><span className="section-number">{number}</span><h2 id={`${id}-title`}>{title}<span className="accent-dot">.</span></h2></div>;
}
export default function Home() {
  const [active, setActive] = useState('overview');
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState(false);
  const [demoPlaying, setDemoPlaying] = useState(false);
  const [frontendPlaying, setFrontendPlaying] = useState(false);
  const demoRef = useRef<HTMLVideoElement>(null);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => {
    const observer = new IntersectionObserver(entries => { entries.forEach(entry => { if (entry.isIntersecting) setActive(entry.target.id); }); }, { rootMargin: '-15% 0px -55% 0px' });
    sections.forEach(([id]) => { const el = document.getElementById(id); if (el) observer.observe(el); });
    return () => { observer.disconnect(); if (timer.current) clearTimeout(timer.current); };
  }, []);
  async function copyClone() {
    try { await navigator.clipboard.writeText(`git clone ${repo}.git`); setCopied(true); setCopyError(false); if (timer.current) clearTimeout(timer.current); timer.current = setTimeout(() => setCopied(false), 2500); }
    catch { setCopyError(true); }
  }
  return <>
    <a className="skip-link" href="#overview">Skip to content</a>
    <header className="site-header"><div className="header-inner"><a href="#top" className="wordmark" aria-label="Geek Mind home">Geek Mind<span>↗</span></a><span className="header-caption">UNIVERSAL EMBODIMENT AGENT RUNTIME</span><a href={repo} target="_blank" rel="noopener noreferrer" className="header-github"><Github size={17} /><span>GitHub</span><ArrowUpRight size={14} /></a></div></header>
    <nav className="page-toc" aria-label="On this page"><span className="toc-caption">CONTENTS</span>{sections.map(([id, label], i) => <a href={`#${id}`} key={id} className={active === id ? 'is-active' : ''} aria-current={active === id ? 'location' : undefined}><span>0{i + 1}</span>{label}</a>)}<div className="toc-bottom"><span className="status-dot" />Perception → Action</div></nav>
    <main id="top" className="page-main">
      <section className="hero" aria-labelledby="project-title">
        <div className="eyebrow"><span className="eyebrow-line" />EMBODIED INTELLIGENCE / PROJECT</div>
        <h1 id="project-title">Geek Mind<span className="title-period">.</span></h1>
        <p className="hero-title">One agent runtime.<br />Multiple embodiments.</p>
        <p className="hero-summary">Connecting multimodal perception, task planning,<br className="desktop-break" /> and physical action in a shared closed loop.</p>
        <div className="hero-meta"><span>Go2</span><span>ARX X5</span><span>Perception-to-action</span></div>
        <div className="project-links"><a href={repo} target="_blank" rel="noopener noreferrer">[<Github size={17} /> Code<ArrowUpRight size={15} />]</a><a href="#demonstration">[<Play size={16} /> Demo<ArrowDown size={15} />]</a><a href={`${repo}#architecture`} target="_blank" rel="noopener noreferrer">[<Code2 size={17} /> Documentation<ArrowUpRight size={15} />]</a></div>
        <div className="hero-rule"><span>A SHARED MIND. A PHYSICAL WORLD.</span><a href="#overview" aria-label="Read project overview"><ArrowDown size={19} /></a></div>
      </section>
      <section id="overview" className="content-section" aria-labelledby="overview-title">
        <Heading number="01" title="One runtime, from intent to action" id="overview" />
        <p className="section-intro">Robots have different bodies, sensors, and ways of acting. <strong>Geek Mind gives them a shared high-level task loop.</strong> Voice, text, vision, and robot state become semantic actions; embodiment adapters connect those actions to the physical world and return verified execution results.</p>
        <figure className="frontend-figure"><div className="media-topline"><span><span className="status-dot" />GEEK MIND / OPERATOR INTERFACE</span><button onClick={() => setFrontendPlaying(!frontendPlaying)} aria-label={frontendPlaying ? 'Pause interface demonstration' : 'Play interface demonstration'}>{frontendPlaying ? <Pause size={14} /> : <Play size={14} />}{frontendPlaying ? 'Pause' : 'Play walkthrough'}</button></div><img src={frontendPlaying ? './media/geek-mind-frontend-demo.gif' : './media/frontend-poster.png'} alt="Geek Mind operator interface showing the task workspace, conversation, and robot controls" width="2940" height="1596" className="frontend-image" />{!frontendPlaying && <button className="frontend-play" onClick={() => setFrontendPlaying(true)} aria-label="Play frontend walkthrough"><Play size={22} fill="currentColor" /></button>}<figcaption><span>01 / The operator interface</span><span>Instruction → Context → Action → Feedback</span></figcaption></figure>
      </section>
      <section id="closed-loop" className="content-section" aria-labelledby="closed-loop-title"><Heading number="02" title="Perception is only the beginning" id="closed-loop" /><p className="section-intro">A shared Cortex loop connects what the robot observes to what it does next. Execution feedback updates the context, allowing the task to progress from the latest state.</p><div className="loop-grid">{stages.map(([name, detail, description], i) => <div className="loop-stage" key={name}><div className="stage-top"><span>0{i + 1}</span>{i < 4 ? <MoveRight size={20} /> : <span className="return-symbol">↲</span>}</div><h3>{name}</h3><p className="stage-detail">{detail}</p><p>{description}</p></div>)}</div><div className="feedback-line"><span>↳</span><span>Verified results return to context.</span><span className="line" /><span>↰</span></div><div className="guardrails"><div><span className="eyebrow">THROUGHOUT THE LOOP</span><h3>Execution with boundaries.</h3></div><p>Configuration validation. Hardware preflight. Fresh inputs. Bounded execution. Result verification. Cancellation.</p></div></section>
      <section id="architecture" className="content-section" aria-labelledby="architecture-title"><Heading number="03" title="A shared mind, a layered system" id="architecture" /><p className="section-intro">From hardware and background services to language-aligned context and user interaction, each layer has a defined role. Robot-specific sensors and actuators connect through a unified embodiment interface.</p><Dialog><DialogTrigger className="architecture-trigger" aria-label="Enlarge Geek Mind architecture diagram"><img src="./media/geek-mind-architecture.png" width="1800" height="1200" alt="Seven-layer Geek Mind architecture, from hardware and providers to embodiment interface, action orchestration, Cortex planning, context, and user interaction" loading="lazy" /><span className="enlarge-label"><Expand size={15} />Explore full architecture</span></DialogTrigger><DialogContent className="architecture-dialog"><DialogTitle>Geek Mind Architecture</DialogTitle><DialogDescription>The shared planning loop and robot-specific execution layers.</DialogDescription><div className="architecture-scroll"><img src="./media/geek-mind-architecture.png" width="1800" height="1200" alt="Full-size Geek Mind architecture diagram" /></div><a href="./media/geek-mind-architecture.png" target="_blank" rel="noopener noreferrer" className="inline-link">Open original image <ArrowUpRight size={15} /></a></DialogContent></Dialog><p className="figure-caption">02 / System architecture. Shared task context and planning; embodiment-specific execution.</p></section>
      <section id="embodiments" className="content-section" aria-labelledby="embodiments-title"><Heading number="04" title="Different bodies. The same task loop" id="embodiments" /><p className="section-intro">Configuration-driven providers and connectors adapt the runtime to each platform. Select a deployment profile to explore its role.</p><Tabs defaultValue="go2" className="embodiment-tabs"><TabsList variant="line" className="profile-tabs" aria-label="Deployment profiles">{profiles.map(p => <TabsTrigger value={p.id} key={p.id}>{p.label}</TabsTrigger>)}</TabsList>{profiles.map(p => <TabsContent value={p.id} key={p.id} className="profile-panel"><div className={`hardware-visual ${p.id === 'combined' ? 'combined' : ''}`}><span className="hardware-label">{p.kind}</span><img src={`./media/${p.image}`} alt={p.alt} width="600" height="600" loading="lazy" />{p.id === 'combined' && <img className="second-hardware" src="./media/arx-x5.png" width="400" height="400" alt="ARX X5 arm for manipulation" loading="lazy" />}<span className="hardware-index">{p.id === 'go2' ? 'E—01' : p.id === 'arx' ? 'E—02' : 'E—01 + E—02'}</span></div><div className="profile-copy"><span className="eyebrow">{p.kind}</span><h3>{p.title}</h3><p>{p.description}</p><ul className="capability-list">{p.tags.map(tag => <li key={tag}><Check size={15} />{tag}</li>)}</ul><a href={`${repo}/blob/main/${p.doc}`} target="_blank" rel="noopener noreferrer" className="inline-link">Deployment guide <ArrowUpRight size={16} /></a><p className="profile-note">{p.note}</p></div></TabsContent>)}</Tabs></section>
      <section id="demonstration" className="content-section" aria-labelledby="demonstration-title"><Heading number="05" title="Out of the interface. Into the world" id="demonstration" /><div className="demo-layout"><div className="demo-copy"><span className="eyebrow">PROJECT DEMONSTRATION</span><h3>From a request<br />to a real-world task.</h3><p>See Geek Mind in a physical environment, bringing the runtime’s perception, planning, and execution path together.</p><button className="watch-button" onClick={() => { if (demoPlaying) demoRef.current?.pause(); else void demoRef.current?.play().catch(() => {}); }}>{demoPlaying ? <Pause size={17} /> : <Play size={17} />}{demoPlaying ? 'Pause demonstration' : 'Watch demonstration'}<ArrowRight size={17} /></button><p className="demo-note">Original project video · Chinese narration</p></div><figure className="demo-video"><video ref={demoRef} controls playsInline preload="none" poster="./media/geek-mind-demo-cover.jpg" onPlay={() => setDemoPlaying(true)} onPause={() => setDemoPlaying(false)} onEnded={() => setDemoPlaying(false)} aria-label="Geek Mind real-world project demonstration"><source src="./media/geek-mind-demo.mp4" type="video/mp4" />Your browser does not support video. <a href="./media/geek-mind-demo.mp4">Download the demonstration.</a></video><figcaption>03 / Geek Mind project demonstration</figcaption></figure></div></section>
      <section id="resources" className="content-section resources" aria-labelledby="resources-title"><Heading number="06" title="Explore the project" id="resources" /><div className="resource-grid"><a href={repo} target="_blank" rel="noopener noreferrer"><Github size={22} /><h3>Source & documentation</h3><p>Runtime, configurations, deployment guides, and project media.</p><span>View on GitHub <ArrowUpRight size={18} /></span></a><a href="https://cn.chinadaily.com.cn/a/202608/04/WS6a718c1aa310d709c2fc1665.html" target="_blank" rel="noopener noreferrer"><span className="press-mark">中国日报网</span><h3>Geek Mind at APEC Digital Week</h3><p>Project coverage from China Daily.</p><span>Read the coverage <ArrowUpRight size={18} /></span></a></div><div className="clone-row"><code>git clone https://github.com/awesomeNabi/Geek-Mind.git</code><button onClick={copyClone} aria-label={copied ? 'Clone command copied' : 'Copy clone command'}>{copied ? <Check size={17} /> : <Copy size={17} />}<span>{copied ? 'Copied' : 'Copy'}</span></button></div><span className="copy-feedback" role="status">{copyError ? 'Select the command above to copy it manually.' : copied ? 'Clone command copied to clipboard.' : ''}</span><p className="deployment-note">Real-robot deployment is hardware-specific. Follow the matching guide, supervise operation, and keep a working emergency stop available.</p></section>
      <footer><div className="footer-main"><a href="#top" className="wordmark">Geek Mind<span>↗</span></a><span>One Agent Runtime · Multiple Embodiments</span><a href="#top" className="back-top">Back to top <ChevronUp size={16} /></a></div><div className="footer-notes"><p>Content & project media: <a href={repo} target="_blank" rel="noopener noreferrer">Geek-Mind repository</a>. Hardware imagery: <a href="https://shop.unitree.com/products/unitree-go2" target="_blank" rel="noopener noreferrer">Unitree Robotics</a> & <a href="https://tidybot2.github.io/docs/bom/" target="_blank" rel="noopener noreferrer">TidyBot++</a> (<a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">CC BY 4.0</a>; cropped in source).</p><p>Page design inspired by <a href="https://robbyant-research.github.io/Zero-WAM/" target="_blank" rel="noopener noreferrer">Zero-WAM</a>.</p></div></footer>
    </main>
  </>;
}
